[package]
name = "identity_core"
version = "0.1.0"
authors = ["IOTA Identity"]
edition = "2018"
description = "The core traits and types for the identity-rs library."
readme = "../README.md"
repository = "https://github.com/iotaledger/identity.rs"
license = "Apache-2.0"
keywords = ["iota", "tangle", "identity"]
homepage = "https://www.iota.org"

[dependencies]
anyhow = { version = "1.0", default-features = false }
async-trait = { version = "0.1", default-features = false }
base64 = { version = "0.12", default-features = false, features = ["std"] }
bs58 = { version = "0.3", default-features = false, features = ["std"] }
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
did_doc = { git = "https://github.com/l1h3r/did_doc", rev = "c61c0457eea7a453949a877f1dde92878a23dd24", default-features = false, features = ["std"] }
did_url = { version = "0.1", default-features = false, features = ["std", "serde"] }
ed25519-zebra = { version = "2.2", default-features = false }
hex = { version = "0.4", default-features = false , features = ["std"] }
identity_diff = { version = "=0.1.0", path = "../identity_diff", default-features = false }
lazy_static = { version = "1.4", default-features = false }
rand = { version = "0.7", default-features = false, features = ["getrandom"] }
serde = { version = "1.0", default-features = false, features = ["std", "derive"] }
serde_jcs = { version = "0.1", default-features = false }
serde_json = { version = "1.0", default-features = false, features = ["preserve_order", "std"] }
sha2 = { version = "0.9", default-features = false }
thiserror = { version = "1.0", default-features = false }
zeroize = { version = "1.1", default-features = false }
