[package]
name = "identity-diff"
version = "0.1.0"
authors = ["IOTA Identity"]
edition = "2018"
description = "The `Diff` trait for the identity-rs library."
readme = "../README.md"
repository = "https://github.com/iotaledger/identity.rs"
license = "Apache-2.0"
keywords = ["iota", "tangle", "identity"]
homepage = "https://www.iota.org"

[dependencies]
anyhow = { version = "1.0" }
did_doc = { git = "https://github.com/l1h3r/did_doc", rev = "c61c0457eea7a453949a877f1dde92878a23dd24", default-features = false, features = ["std"] }
did_url = { version = "0.1", default-features = false, features = ["std", "serde"] }
identity-derive = { version = "=0.1.0", path = "derive" }
serde = { version = "1.0", features = [ "derive" ] }
serde_json = { version = "1.0" }
thiserror = { version = "1.0" }

[dev-dependencies]
serde_json = "1.0"
